In [5]:
'''
Author: Aadil Hussain
Built on: Python 3.10.11
'''

import pandas as pd

POKEDATA_FILEPATH = 'Assignment5_Pokemon_Data.csv'

pokemon_data = pd.read_csv(POKEDATA_FILEPATH)

# Download the Pokémon Dataset and create a Jupyter Notebook that displays the following answers to these questions
# (NOTE: create a DataFrame to answer these questions)

In [6]:
# Part A - Formatting the Data: (All changes should be made to the existing (original) dataframe)
    # 1. Format the Database so it shows a maximum of two decimal places
    # 2. Format the Database so it shows all columns
    # 3. Display the number of rows and columns in the Dataframe
    # 4. Change the ‘Generation’ Column name to ‘Gen’
    # 5. Set a default value of ‘NA’ for all missing cells in the Database
    # 6. Change the dType of the TYPE 2 series to Category
    # 7. Display the Datatype of each of the series in the Dataframe (hint: info)
    # 8. Create a NEW Dataframe with 2 Pokemon you Make up: Add this new Dataframe and the existing Pokemon Dataframe together to create your new working Dataframe all_pokemon
    # 9. Display the last 10 pokemon of of the all_pokemon dataframe

In [7]:
# PartA
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.max_columns', None)
print("Number of rows:", pokemon_data.shape[0])
print("Number of columns:", pokemon_data.shape[1])
pokemon_data.rename(columns={'Generation': 'Gen'}, inplace=True)
pokemon_data.fillna('NA', inplace=True)
pokemon_data['Type 2'] = pokemon_data['Type 2'].astype('category')
pokemon_data.info()

# uh question 8 is kinda weird oop
# Create a new DataFrame with two Pokemon
new_pokemon_data = pd.DataFrame({
    'NAME': ['Fictimon1', 'Fictimon2'],
    'Type 1': ['Fairy', 'Dragon'],
    'Type 2': ['None', 'Fire'],
    'HP': [80, 90],
    'Attack': [100, 110],
    'Defense': [75, 85],
    'Sp. Atk': [120, 130],
    'Sp. Def': [80, 90],
    'Speed': [100, 110],
    'Generation': [8, 8],
    'Legendary': [False, False]
})
# Display the new DataFrame
print("\nnew_pokemon_data:")
print(new_pokemon_data)
# Concatenate the two DataFrames to create 'all_pokemon'
all_pokemon = pd.concat([pokemon_data, new_pokemon_data], ignore_index=True)

# q9
print(all_pokemon.tail(10))

all_pokemon.head()

Number of rows: 800
Number of columns: 12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   #          800 non-null    int64
 1   Name       800 non-null    object
 2   Type 1     800 non-null    object
 3   Type 2     800 non-null    category
 4   HP         800 non-null    int64
 5   Attack     800 non-null    int64
 6   Defense    800 non-null    int64
 7   Sp. Atk    800 non-null    int64
 8   Sp. Def    800 non-null    int64
 9   Speed      800 non-null    int64
 10  Gen        800 non-null    int64
 11  Legendary  800 non-null    bool
dtypes: bool(1), category(1), int64(8), object(2)
memory usage: 64.9+ KB

new_pokemon_data:
        NAME  Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  Fictimon1   Fairy   None  80     100       75      120       80    100
1  Fictimon2  Dragon   Fire  90     110       85      130       90    110

   Generation  Legendary
0           8      False
1           8      False
         #                 Name   Type 1  Type 2   HP  Attack  Defense  \
792 716.00              Xerneas    Fairy      NA  126     131       95
793 717.00              Yveltal     Dark  Flying  126     131       95
794 718.00     Zygarde50% Forme   Dragon  Ground  108     100      121
795 719.00              Diancie     Rock   Fairy   50     100      150
796 719.00  DiancieMega Diancie     Rock   Fairy   50     160      110
797 720.00  HoopaHoopa Confined  Psychic   Ghost   80     110       60
798 720.00   HoopaHoopa Unbound  Psychic    Dark   80     160       60
799 721.00            Volcanion     Fire   Water   80     110      120
800    NaN                  NaN    Fairy    None   80     100       75
801    NaN                  NaN   Dragon    Fire   90     110       85

     Sp. Atk  Sp. Def  Speed  Gen  Legendary       NAME  Generation
792      131       98     99 6.00       True        NaN         NaN
793      131       98     99 6.00       True        NaN         NaN
794       81       95     95 6.00       True        NaN         NaN
795      100      150     50 6.00       True        NaN         NaN
796      160      110    110 6.00       True        NaN         NaN
797      150      130     70 6.00       True        NaN         NaN
798      170      130     80 6.00       True        NaN         NaN
799      130       90     70 6.00       True        NaN         NaN
800      120       80    100  NaN      False  Fictimon1        8.00
801      130       90    110  NaN      False  Fictimon2        8.00

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Gen,Legendary,NAME,Generation
0,1.00,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1.00,False,NaN,NaN
1,2.00,Ivysaur,Grass,Poison,60,62,63,80,80,60,1.00,False,NaN,NaN
2,3.00,Venusaur,Grass,Poison,80,82,83,100,100,80,1.00,False,NaN,NaN
3,3.00,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1.00,False,NaN,NaN
4,4.00,Charmander,Fire,NA,39,52,43,60,50,65,1.00,False,NaN,NaN

In [8]:
# Part B – Displaying Information Create the following new dataframes from your original pokemon dataframe:
    # 1. Display all info from the first three Pokémon
    # 2. Display all info from the last ten Pokémon
    # 3. Display just the ‘Name’, ‘Type 1’, and ‘HP’ of pokemon 400-410
    # 4. Display the mean HP (use a markdown to display in a statement)
    # 5. Display the max attack damage (use a markdown to display in a statement)
    # 6. Display a separate count of each pokemon type (type1 only)
    # 7. Display a separate count of each pokemon type BUT ONLY for Gen 1 and 2 (type 1 only)

In [9]:
#PartB
first_three_pokemon = all_pokemon.head(3)
print("\nfirst three pokemon:"); print(first_three_pokemon)
last_ten_pokemon = all_pokemon.tail(10)
print("\nlast ten pokemon:"); print(last_ten_pokemon)
the_chosen_pokemon = all_pokemon.loc[400:410, ['Name', 'Type 1', 'HP']]
print("\n400-410 pokemon:"); print(the_chosen_pokemon)
mean_hp = all_pokemon['HP'].mean()
print(f"\nThe mean HP of all Pokémon is **{mean_hp:.2f}**.")
max_attack_damage = all_pokemon['Attack'].max()
print(f"\nThe maximum attack damage of all Pokémon is **{max_attack_damage}**.")
type_counts_df = all_pokemon.groupby('Type 1').size().reset_index(name='Count')
print("\nsep cound of each pokemon type (type1 col only):")
print(type_counts_df)

#dam bruh this question 7 got me trippinnn (this was done at 3am, pls excuse me bad code)
# hmm filter the DataFrame for Generation 1 and 2
gen1_2_pokemon = all_pokemon[all_pokemon['Generation'].isin([1, 2])]
# lemme create a new DataFrame with counts of each Pokemon type (Type 1 only) for Gen 1 and 2
type_counts_gen1_2_df = gen1_2_pokemon.groupby('Type 1').size().reset_index(name='Count')
#here we go
print("\nsep count each pokemion type only gen 1&2"); print(type_counts_gen1_2_df)

first three pokemon:
     #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0 1.00  Bulbasaur  Grass  Poison  45      49       49       65       65
1 2.00    Ivysaur  Grass  Poison  60      62       63       80       80
2 3.00   Venusaur  Grass  Poison  80      82       83      100      100

   Speed  Gen  Legendary NAME  Generation
0     45 1.00      False  NaN         NaN
1     60 1.00      False  NaN         NaN
2     80 1.00      False  NaN         NaN

last ten pokemon:
         #                 Name   Type 1  Type 2   HP  Attack  Defense  \
792 716.00              Xerneas    Fairy      NA  126     131       95
793 717.00              Yveltal     Dark  Flying  126     131       95
794 718.00     Zygarde50% Forme   Dragon  Ground  108     100      121
795 719.00              Diancie     Rock   Fairy   50     100      150
796 719.00  DiancieMega Diancie     Rock   Fairy   50     160      110
797 720.00  HoopaHoopa Confined  Psychic   Ghost   80     110       60
798 720.00   HoopaHoopa Unbound  Psychic    Dark   80     160       60
799 721.00            Volcanion     Fire   Water   80     110      120
800    NaN                  NaN    Fairy    None   80     100       75
801    NaN                  NaN   Dragon    Fire   90     110       85

     Sp. Atk  Sp. Def  Speed  Gen  Legendary       NAME  Generation
792      131       98     99 6.00       True        NaN         NaN
793      131       98     99 6.00       True        NaN         NaN
794       81       95     95 6.00       True        NaN         NaN
795      100      150     50 6.00       True        NaN         NaN
796      160      110    110 6.00       True        NaN         NaN
797      150      130     70 6.00       True        NaN         NaN
798      170      130     80 6.00       True        NaN         NaN
799      130       90     70 6.00       True        NaN         NaN
800      120       80    100  NaN      False  Fictimon1        8.00
801      130       90    110  NaN      False  Fictimon2        8.00

400-410 pokemon:
                        Name  Type 1   HP
400                  Walrein     Ice  110
401                 Clamperl   Water   35
402                  Huntail   Water   55
403                 Gorebyss   Water   55
404                Relicanth   Water  100
405                  Luvdisc   Water   43
406                    Bagon  Dragon   45
407                  Shelgon  Dragon   65
408                Salamence  Dragon   95
409  SalamenceMega Salamence  Dragon   95
410                   Beldum   Steel   40

The mean HP of all Pokémon is **69.30**.

The maximum attack damage of all Pokémon is **190**.

sep cound of each pokemon type (type1 col only):
      Type 1  Count
0        Bug     69
1       Dark     31
2     Dragon     33
3   Electric     44
4      Fairy     18
5   Fighting     27
6       Fire     52
7     Flying      4
8      Ghost     32
9      Grass     70
10    Ground     32
11       Ice     24
12    Normal     98
13    Poison     28
14   Psychic     57
15      Rock     44
16     Steel     27
17     Water    112

sep count each pokemion type only gen 1&2
Empty DataFrame
Columns: [Type 1, Count]
Index: []

The mean HP of all Pokémon is **69.3**.
The maximum attack damage of all Pokémon is **190**.

In [10]:
# Part C – Querying/Aggregating Data and Visualization: For Each Question – display Data in a relevant graph:
    # 1. Visualize (graph) the pokemon according to ‘Type 1’. Ie. bug, water etc.
    # 2. Display all the pokemon who are 4th Gen and have an HP over 90 a. Tell me the overall number as well
    # 3. Query and visualize just the First Generation by Type 1
    # 4. Validate whether the following statement is True through visualization: ‘As a pokemon’s Attack is increased, it’s defense also increases.’
    # 5. Visualize the data between Legendary and Non-Legendary Pokemon
    # 6. Categorize the pokemon by ‘Type 1’, and calculate the mean HP of each ‘Type.’ Visualize the Results. What type of pokemon has highest mean HP?
    # 7. Query the max Attack of each Pokemon by Type. Visualize the data.
    # 8. Is there a correlation between HP and Defense? Visualize data to explain your stance.

In [11]:
# Part C # 1.

# Create a bar plot for the distribution of Pokemon types (Type 1)
type_counts = all_pokemon['Type 1'].value_counts()
print(type_counts)
#pip install matplotlib?
type_counts.plot(kind='pie') #why is my plot not plotting?

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       33
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        18
Flying        4
Name: Type 1, dtype: int64

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.